import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./sections/navbar";

 const calibri = localFont({
  src: "./fonts/calibri-regular.ttf",
  variable: "--font-calibri",
});


export const calibri_bold = localFont({
  src: "./fonts/calibri-bold.ttf",
  variable: "--font-calibri-bold",
});

export const calibri_bold_italic = localFont({
  src: "./fonts/calibri-bold-italic.ttf",
  variable: "--font-calibri-bold-italic",
});

export const venus = localFont({
  src: "./fonts/venusrisingrg-bold-italic.ttf",
  variable: "--font-venus",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" >
      <body
        className={`${calibri.className} `}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
